export type SeedStatus = 'draft' | 'active' | 'paused' | 'retired' | 'prohibited';
export type EvidenceTier = 'A' | 'B' | 'C' | 'D' | 'X';
export type SourceType = 'guideline' | 'meta_analysis' | 'systematic_review' | 'rct' | 'professional_manual' | 'coaching_reference';

export interface SeedSource {
  sourceType: SourceType;
  citationText: string;
  sourceUrl: string;
  publicationYear: number;
  supports: string;
  limitations: string;
  licenseNotes: string;
  reviewed: boolean;
  reviewedBy: string;
}

export interface CatalogSeedCard {
  code: string;
  version: number;
  status: SeedStatus;
  titleAr: string;
  shortDescriptionAr: string;
  framework: string;
  evidenceTier: EvidenceTier;
  contentOrigin: string;
  licensingStatus: 'cleared_original' | 'licensed' | 'review_required' | 'restricted';
  targetNeeds: string[];
  targetPatterns: string[];
  eligibleStates: string[];
  journeyDomains: string[];
  exclusions: string[];
  contraindicationNotesAr: string;
  durationMin: number;
  stepsAr: string[];
  actionTemplateAr: string;
  measurementSpec: Record<string, unknown>;
  followUpSpec: Record<string, unknown>;
  fallbackCode: string | null;
  requiresUserConfirmation: boolean;
  scientificReviewStatus: 'pending' | 'reviewed' | 'rejected';
  clinicalBoundaryReviewStatus: 'pending' | 'reviewed' | 'rejected';
  requiresHumanSupport: boolean;
  sources: SeedSource[];
}

const S = {
  WHO_SELF_HELP_2026: {
    sourceType: 'guideline' as const,
    citationText: 'World Health Organization. Psychological self-help interventions: delivering self-help for individuals, featuring Step-by-Step and Doing What Matters in Times of Stress. 2026.',
    sourceUrl: 'https://www.who.int/publications/i/item/9789240120785',
    publicationYear: 2026,
    supports: 'Structured low-intensity psychological self-help and guided/unguided delivery with appropriate scope boundaries.',
    limitations: 'Does not validate Malaak wording or authorize copying manual scripts; not a substitute for specialist treatment when impairment/risk is high.',
    licenseNotes: 'WHO 2026 manual uses non-commercial terms by default; Malaak uses original wording and requires separate commercial permission before copying protected material.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  WHO_DWM: {
    sourceType: 'guideline' as const,
    citationText: 'World Health Organization. Doing What Matters in Times of Stress: An Illustrated Guide. 2020.',
    sourceUrl: 'https://www.who.int/publications-detail-redirect/9789240003927',
    publicationYear: 2020,
    supports: 'Low-intensity principles such as grounding, unhooking from difficult thoughts, making room for emotions, values-guided action and self-kindness.',
    limitations: 'Supports underlying principles, not Malaak-specific scripts or effectiveness claims for this app.',
    licenseNotes: 'Do not copy protected scripts/illustrations; Malaak wording is original.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  NICE_GAD: {
    sourceType: 'guideline' as const,
    citationText: 'NICE CG113. Generalised anxiety disorder and panic disorder in adults: management. Recommendations.',
    sourceUrl: 'https://www.nice.org.uk/guidance/cg113/chapter/Recommendations',
    publicationYear: 2020,
    supports: 'Stepped care, CBT-based low-intensity self-help, routine outcome monitoring, problem-solving/cognitive principles, and stepping up with marked impairment or non-response.',
    limitations: 'Guideline is for diagnosed GAD/panic care; Malaak uses only transdiagnostic low-risk principles and does not diagnose or deliver high-intensity treatment.',
    licenseNotes: 'Principles summarized; no treatment manual text copied.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  SAMHSA_TRAUMA: {
    sourceType: 'guideline' as const,
    citationText: 'SAMHSA. Trauma-Informed Approaches and Programs.',
    sourceUrl: 'https://www.samhsa.gov/mental-health/trauma-violence/trauma-informed-approaches-programs',
    publicationYear: 2026,
    supports: 'Safety, trust/transparency, collaboration, empowerment, voice/choice and avoiding re-traumatization.',
    limitations: 'Trauma-informed principles are not a self-administered trauma-processing protocol.',
    licenseNotes: 'Principles only; no protected clinical protocol copied.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  GROSS_ER: {
    sourceType: 'systematic_review' as const,
    citationText: 'McRae K, Gross JJ. Emotion regulation. Emotion. 2020;20(1):1-9. PMID 31961170.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/31961170/',
    publicationYear: 2020,
    supports: 'Process-based emotion regulation: identify need, select/implement a strategy, then monitor success; cognitive reappraisal is a well-studied strategy.',
    limitations: 'Conceptual review; does not validate a particular app exercise or imply one strategy is universally best.',
    licenseNotes: 'Conceptual principles summarized.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  ASSERT_2026: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Hede JP, Malouff JM, Meynadier J. A Meta-Analysis of Randomised Controlled Trials on the Efficacy of Assertiveness Training for Social Anxiety. 2026.',
    sourceUrl: 'https://link.springer.com/article/10.1007/s41042-026-00297-7',
    publicationYear: 2026,
    supports: 'Assertiveness training can improve assertive behavior in studied populations and supports practicing direct, respectful communication.',
    limitations: 'Population/effects are not equivalent to all relationship contexts; does not justify confrontation where danger is possible.',
    licenseNotes: 'Underlying assertiveness principles summarized in original wording.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  IU_2023: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Wilson EJ, Abbott MJ, Norton AR. The impact of psychological treatment on intolerance of uncertainty in generalized anxiety disorder: A systematic review and meta-analysis. J Anxiety Disord. 2023;97:102729.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/37271039/',
    publicationYear: 2023,
    supports: 'Psychological treatments can reduce intolerance of uncertainty and worry; directly targeting uncertainty may be useful.',
    limitations: 'Evidence concerns GAD treatments; Malaak does not reproduce a full treatment protocol or diagnose GAD.',
    licenseNotes: 'General treatment principle only.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  IU_2024: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Näsling J, et al. Effect of Psychotherapy on Intolerance of Uncertainty: A Systematic Review and Meta-Analysis. 2024. PMID 39036833.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/39036833/',
    publicationYear: 2024,
    supports: 'Psychotherapy can change intolerance of uncertainty, while active-control results and heterogeneity counsel modest claims.',
    limitations: 'Substantial heterogeneity; active-control effects were not consistently significant.',
    licenseNotes: 'General principle only.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  RNT_2025: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Stenzel KL, et al. Efficacy of cognitive behavioral therapy in treating repetitive negative thinking, rumination, and worry - a transdiagnostic meta-analysis. Psychol Med. 2025. PMID 39916353.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/39916353/',
    publicationYear: 2025,
    supports: 'CBT interventions reduce repetitive negative thinking across diagnoses; process-specific approaches can be useful.',
    limitations: 'Does not support endless cognitive debate or reassurance; Malaak uses low-intensity process tools rather than disorder treatment.',
    licenseNotes: 'Principles summarized in original wording.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  ACT_FLEX_2024: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Macri JA, Rogge RD. Examining domains of psychological flexibility and inflexibility as treatment mechanisms in ACT: systematic and meta-analytic review. Clin Psychol Rev. 2024;110:102432.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/38615492/',
    publicationYear: 2024,
    supports: 'ACT-related changes in defusion, acceptance, present-moment awareness and committed action are associated with reduced distress.',
    limitations: 'Mechanism evidence does not validate Malaak or every ACT-derived micro-skill; crisis populations require additional care.',
    licenseNotes: 'General ACT mechanisms summarized; no manual scripts copied.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  ATTACH_2022: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Gillath O, Karantzas GC, Romano D, Karantzas KM. Attachment Security Priming: A Meta-Analysis. Pers Soc Psychol Rev. 2022;26(3):183-241.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/35209765/',
    publicationYear: 2022,
    supports: 'Attachment-security priming has measurable affective, cognitive and behavioral effects and attachment processes can be context-sensitive.',
    limitations: 'Priming evidence does not make attachment categories diagnoses or justify fixed identity labels; Malaak does not use subliminal priming.',
    licenseNotes: 'Attachment concepts summarized; no proprietary assessment copied.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  COUPLES_META: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Rathgeber M, et al. The Efficacy of Emotionally Focused Couples Therapy and Behavioral Couples Therapy: A Meta-Analysis. J Marital Fam Ther. 2019;45(3):447-463.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/29781200/',
    publicationYear: 2019,
    supports: 'Evidence-based couple therapies can improve relationship satisfaction; interaction cycles, behavior change and emotional processes are legitimate intervention targets.',
    limitations: 'Malaak does not deliver full couple therapy and must not use couple communication tools in unsafe/violent relationships.',
    licenseNotes: 'General couple-therapy principles summarized; no manual protocol copied.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  IBCT_REVIEW: {
    sourceType: 'systematic_review' as const,
    citationText: 'Roddy MK, Nowlan KM, Doss BD, Christensen A. Integrative Behavioral Couple Therapy: Theoretical Background, Empirical Research, and Dissemination. Fam Process. 2016;55(3):408-422.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/27226235/',
    publicationYear: 2016,
    supports: 'Combining behavior change with acceptance/contextual understanding is evidence-informed in couple work.',
    limitations: 'Not a license to reproduce IBCT protocols or to treat unsafe relationships as ordinary couple discord.',
    licenseNotes: 'General principles summarized.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  ANGER_META: {
    sourceType: 'meta_analysis' as const,
    citationText: 'DiGiuseppe R, Tafrate RC. Effectiveness of anger treatments for specific anger problems: a meta-analytic review. Clin Psychol Rev. 2003/2004. PMID 14992805.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/14992805/',
    publicationYear: 2004,
    supports: 'Cognitive and behavioral anger treatments show meaningful effects across anger presentations; appraisal and response skills are relevant targets.',
    limitations: 'Older heterogeneous literature; safety risk overrides self-help anger coaching.',
    licenseNotes: 'General anger-management principles summarized.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  SELF_COMP_2023: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Han A, Kim TH. Effects of Self-Compassion Interventions on Reducing Depressive Symptoms, Anxiety, and Stress: A Meta-Analysis. 2023. PMID 37362192.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/37362192/',
    publicationYear: 2023,
    supports: 'Self-compassion interventions show small-to-medium benefits for distress-related outcomes and support compassionate self-responding as an adjunctive skill.',
    limitations: 'Risk of bias was high across included RCTs; not a stand-alone treatment claim or permission to avoid responsibility.',
    licenseNotes: 'General self-compassion principles summarized.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  CHILD_SELF_COMP: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Zhang H, et al. Effects of Childhood Maltreatment on Self-Compassion: A Systematic Review and Meta-Analysis. 2021. PMID 34510982.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/34510982/',
    publicationYear: 2021,
    supports: 'Childhood maltreatment experiences are associated with lower self-compassion, supporting cautious attention to self-criticism/self-compassion in developmental-history work.',
    limitations: 'Association does not establish a single causal pathway or justify reconstructing hidden memories.',
    licenseNotes: 'Research association summarized.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  GRIEF_2024: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Komischke-Konnerup KB, et al. Grief-focused cognitive behavioral therapies for prolonged grief symptoms: A systematic review and meta-analysis. J Consult Clin Psychol. 2024;92(4):236-248.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/38573714/',
    publicationYear: 2024,
    supports: 'CBT-informed approaches can help prolonged grief symptoms; grief-related thoughts/behavior and adaptation are legitimate targets.',
    limitations: 'Malaak does not diagnose or treat prolonged grief disorder and does not use exposure-style grief treatment protocols.',
    licenseNotes: 'General principles only.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
  PERFECTION_2021: {
    sourceType: 'meta_analysis' as const,
    citationText: 'Galloway R, et al. The efficacy of randomised controlled trials of CBT for perfectionism: a systematic review and meta-analysis. 2021/2022. PMID 34346282.',
    sourceUrl: 'https://pubmed.ncbi.nlm.nih.gov/34346282/',
    publicationYear: 2021,
    supports: 'CBT approaches can reduce perfectionism-related processes and support testing rigid rules/standards.',
    limitations: 'Does not validate the feminine-balance taxonomy; evidence belongs to the perfectionism/control component only.',
    licenseNotes: 'General CBT principles summarized.',
    reviewed: true,
    reviewedBy: 'Malaak V5 evidence review',
  },
};

const basicMeasure = (primary = 'intensity') => ({
  before: [`${primary}_before`],
  after: [`${primary}_after`],
  outcome: ['action_outcome','user_helpfulness'],
});
const follow = (timing: 'later_today' | 'tomorrow' | 'after_event' = 'later_today', prompt = 'شو صار بعد ما جربتي الخطوة؟') => ({ timing, prompt });

function card(input: Omit<CatalogSeedCard, 'version' | 'licensingStatus' | 'scientificReviewStatus' | 'clinicalBoundaryReviewStatus' | 'requiresHumanSupport'> & Partial<Pick<CatalogSeedCard, 'version' | 'licensingStatus' | 'scientificReviewStatus' | 'clinicalBoundaryReviewStatus' | 'requiresHumanSupport'>>): CatalogSeedCard {
  return {
    version: 1,
    licensingStatus: 'cleared_original',
    scientificReviewStatus: input.status === 'active' ? 'reviewed' : 'reviewed',
    clinicalBoundaryReviewStatus: input.status === 'active' ? 'reviewed' : 'pending',
    requiresHumanSupport: false,
    ...input,
  };
}

const traumaBoundary = [
  'Do not use for trauma exposure, memory recovery, imaginal reliving, EMDR, or to infer that a hidden event must have occurred.',
];
const dangerBoundary = ['Do not use direct confrontation when interpersonal violence, coercion, stalking, or credible danger may be present.'];

export const catalogSeed: CatalogSeedCard[] = [
  card({code:'REG_GROUND_001',status:'active',titleAr:'تثبيت الحاضر',shortDescriptionAr:'إرجاع الانتباه للحاضر قبل القرار أو التصرف.',framework:'grounding / distress tolerance',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['regulation','safety'],targetPatterns:['anger_escalation','attachment_alarm','reassurance_loop','rumination','unknown'],eligibleStates:['high_activation','moderate_activation','unknown'],journeyDomains:['emotional-state','inner-peace'],exclusions:['Not trauma processing.'],contraindicationNotesAr:'إذا زاد التركيز الحسي الضيق بدل أن يخففه، انتقلي لأداة تنظيم أخرى.',durationMin:2,stepsAr:['وقفي القرار أو الرسالة للحظة.','سمّي 3 أشياء شايفتيها وشيئين عم تلمسيهم وشي عم تسمعيه.','قيّمي إذا الشدة نزلت ولو درجة.'],actionTemplateAr:'خدي دقيقتين تثبيت قبل أي تصرف جديد.',measurementSpec:basicMeasure(),followUpSpec:follow('later_today'),fallbackCode:null,requiresUserConfirmation:false,sources:[S.WHO_DWM,S.GROSS_ER]}),
  card({code:'REG_MOVE_002',status:'active',titleAr:'حركة قصيرة للتنظيم',shortDescriptionAr:'استخدام حركة هادئة قصيرة لتخفيف الاستنفار.',framework:'behavioral regulation',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['regulation','rest'],targetPatterns:['anger_escalation','rumination','control_overdrive','unknown'],eligibleStates:['high_activation','moderate_activation'],journeyDomains:['inner-peace','anger'],exclusions:['Modify when movement is medically inappropriate.'],contraindicationNotesAr:'إذا الحركة غير مناسبة صحيًا أو تزيد الدوخة/الألم، استخدمي تثبيت الحاضر بدلها.',durationMin:5,stepsAr:['ابتعدي عن الشاشة أو الحوار الساخن.','امشي أو حرّكي جسمك بهدوء بدون تفريغ عدواني.','ارجعي قيّمي شدتك قبل الخطوة التالية.'],actionTemplateAr:'اعملي حركة هادئة 5 دقائق ثم قيّمي شدتك من جديد.',measurementSpec:basicMeasure(),followUpSpec:follow('later_today'),fallbackCode:'REG_GROUND_001',requiresUserConfirmation:false,sources:[S.WHO_SELF_HELP_2026,S.GROSS_ER]}),
  card({code:'REG_BREATHE_003',status:'active',titleAr:'تنفّس بطيء مريح',shortDescriptionAr:'إبطاء التنفس بلطف بدون فرض نمط صارم.',framework:'low-intensity regulation',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['regulation','rest'],targetPatterns:['unknown','rumination','anger_escalation'],eligibleStates:['moderate_activation','high_activation'],journeyDomains:['emotional-state','inner-peace'],exclusions:['Stop if breath focus increases panic, dizziness, or distress.'],contraindicationNotesAr:'مو مطلوب تعملي حبس نفس أو أرقام قاسية. إذا التركيز على النفس بيوترك، منبدّل الأداة فورًا.',durationMin:2,stepsAr:['خلي الزفير أبطأ شوي من المعتاد بدون إجبار.','اعملي عدة أنفاس مريحة فقط.','إذا زاد الضيق، وقفي وانتقلي للتثبيت الحسي.'],actionTemplateAr:'جربي دقيقتين تنفّس مريح فقط إذا جسمك متقبله.',measurementSpec:basicMeasure(),followUpSpec:follow('later_today'),fallbackCode:'REG_GROUND_001',requiresUserConfirmation:true,sources:[S.WHO_SELF_HELP_2026]}),
  card({code:'EMO_NAME_001',status:'active',titleAr:'سمّي الشعور تقريبًا',shortDescriptionAr:'تحديد عائلة الشعور بدون ضغط للوصول لكلمة مثالية.',framework:'emotion awareness / emotion regulation',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['understanding','clarity'],targetPatterns:['unknown','unmet_need','anger_escalation'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['emotional-state'],exclusions:['Do not force precision or interpret the emotion as diagnosis.'],contraindicationNotesAr:'إذا ما قدرتي تسمّيه، منبدأ من الجسم أو الرغبة بالسلوك بدل التخمين.',durationMin:3,stepsAr:['اختاري أقرب عائلة: خوف/غضب/حزن/خجل/غيرة/راحة/غيرها.','قولي قدّيش شدته تقريبًا.','اتركي احتمال إن الاسم يتغير بعد ما نفهم الموقف.'],actionTemplateAr:'سمّي أقرب شعور وشدته، حتى لو الاسم مو مثالي.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('later_today','بعد ما سميتي الشعور، صار أوضح شو محتاجة؟'),fallbackCode:'REG_GROUND_001',requiresUserConfirmation:false,sources:[S.GROSS_ER]}),
  card({code:'EMO_CHAIN_002',status:'active',titleAr:'سلسلة الموقف والمشاعر',shortDescriptionAr:'فصل الحدث والتفسير والمشاعر والجسم والرغبة والسلوك.',framework:'CBT-informed emotion chain',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['understanding','clarity'],targetPatterns:['anger_escalation','conflict_cycle','thought_fusion','unknown'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['emotional-state','anger'],exclusions:['Not for deep trauma reconstruction.'],contraindicationNotesAr:'منستخدم الحاضر والمعلومات المعروفة فقط، وما منرجّعك لذكريات صادمة للتفسير.',durationMin:7,stepsAr:['شو صار كحدث؟','شو فسّره عقلك؟','شو شعرتي بالجسم والمشاعر؟','شو كانت الرغبة؟','شو عملتي أو بدك تعملي؟'],actionTemplateAr:'اكتبي السلسلة بخمس أسطر قبل ما تحكمي على حالك.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow','أي جزء من السلسلة كان أسهل نقطة للتغيير؟'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:false,sources:[S.GROSS_ER,S.NICE_GAD]}),

  card({code:'LOAD_SORT_001',status:'active',titleAr:'الآن / لاحقًا / مو بإيدي',shortDescriptionAr:'ترتيب الحمل بدل التعامل مع كل شيء كأنه عاجل.',framework:'problem solving / prioritization',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['clarity','rest','autonomy'],targetPatterns:['control_overdrive','practical_problem','rumination'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['inner-peace'],exclusions:['Do not classify safety threats as “not in my control” and ignore them.'],contraindicationNotesAr:'إذا في خطر أو التزام عاجل حقيقي، الأولوية للسلامة/الفعل الضروري.',durationMin:6,stepsAr:['اكتبي الأشياء اللي فوق بعض.','حطي كل واحدة: الآن / لاحقًا / مو بإيدي الآن.','اختاري شي واحد فقط من خانة الآن.'],actionTemplateAr:'رتّبي الحمل بثلاث خانات وخدي مهمة واحدة فقط هلق.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('later_today'),fallbackCode:'PROBLEM_SOLVE_001',requiresUserConfirmation:false,sources:[S.NICE_GAD,S.WHO_SELF_HELP_2026]}),
  card({code:'CONTROL_CIRCLE_001',status:'active',titleAr:'شو بإيدي وشو مو بإيدي',shortDescriptionAr:'تمييز الفعل الممكن عن محاولة السيطرة على غير القابل للسيطرة.',framework:'problem solving / psychological flexibility',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['autonomy','clarity'],targetPatterns:['control_overdrive','rumination','practical_problem'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['inner-peace','feminine-balance'],exclusions:['Does not mean accepting abuse, danger, or rights violations without action.'],contraindicationNotesAr:'القبول بعدم السيطرة على شخص ما لا يعني التنازل عن الحدود أو طلب الحماية.',durationMin:6,stepsAr:['حددي الشي اللي بدك تتحكمي فيه.','شو جزء فعلي بإيدك؟','شو جزء قرار شخص آخر أو واقع ما فيكي تضمنيه؟','اعملي فعل واحد بإيدك واتركي الباقي بدون مطاردة.'],actionTemplateAr:'اختاري فعل واحد تحت سيطرتك واتركي محاولة إدارة رد فعل الآخر.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'PROBLEM_SOLVE_001',requiresUserConfirmation:false,sources:[S.ACT_FLEX_2024,S.NICE_GAD]}),
  card({code:'REST_RECOVERY_001',status:'active',titleAr:'حد أدنى للتعافي اليوم',shortDescriptionAr:'خطة صغيرة للراحة عندما الحمل أعلى من قدرة اليوم.',framework:'behavioral self-care / recovery planning',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['rest','support'],targetPatterns:['control_overdrive','anger_escalation','unknown'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['inner-peace','feminine-balance'],exclusions:['Not a medical treatment for persistent fatigue, insomnia, or other health symptoms.'],contraindicationNotesAr:'إذا التعب شديد/مستمر أو معه أعراض صحية مقلقة، التطبيق ما بيستبدل التقييم الطبي.',durationMin:5,stepsAr:['حددي شو الضروري جدًا اليوم.','شيلِي أو أجّلي شي واحد غير ضروري.','اختاري استراحة قصيرة واقعية أو اطلبي دعمًا محددًا.'],actionTemplateAr:'خففي حمل واحد وخدي استراحة واقعية صغيرة اليوم.',measurementSpec:basicMeasure('intensity'),followUpSpec:follow('tomorrow','هل خف الحمل فعلًا ولا بقيت الخطة على الورق؟'),fallbackCode:'LOAD_SORT_001',requiresUserConfirmation:false,sources:[S.WHO_SELF_HELP_2026]}),

  card({code:'NEED_NAME_001',status:'active',titleAr:'سمّي الحاجة',shortDescriptionAr:'فهم الشي الناقص قبل اختيار الحل.',framework:'needs clarification / self-determination-informed',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['understanding','connection','rest','respect','autonomy','support'],targetPatterns:['unmet_need','people_pleasing','conflict_cycle','unknown'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['needs'],exclusions:['A need does not create entitlement to control another person.'],contraindicationNotesAr:'منميّز بين صحة الحاجة وبين حق الشخص الآخر بالقبول أو الرفض ضمن الأمان والحقوق.',durationMin:5,stepsAr:['سمّي الشعور الأقرب.','اسألي شو كان ناقص بالموقف.','اختاري كلمة حاجة: راحة/قرب/وضوح/احترام/استقلال/دعم/غيرها.'],actionTemplateAr:'سمّي حاجتك بكلمة واضحة قبل ما تختاري الحل.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('later_today'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:false,sources:[S.WHO_SELF_HELP_2026]}),
  card({code:'NEED_STRATEGY_002',status:'active',titleAr:'الحاجة مو هي الحل',shortDescriptionAr:'فصل الحاجة عن الاستراتيجية التي نطلبها من الآخر.',framework:'needs clarification / autonomy-supportive coaching',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['understanding','autonomy','connection'],targetPatterns:['unmet_need','reassurance_loop','control_overdrive'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['needs'],exclusions:['Do not use to minimize legitimate agreements, duties, or safety needs.'],contraindicationNotesAr:'مثلاً الأمان حاجة؛ مراقبة هاتف شخص آخر استراتيجية مو حق تلقائي.',durationMin:5,stepsAr:['اكتبي الشي اللي بدك الشخص يعمله.','اسألي: شو الحاجة تحته؟','طلّعي طريقتين أو ثلاث لتلبية جزء من الحاجة بدون السيطرة على الآخر.'],actionTemplateAr:'حوّلي طلبك من “لازم تعمل” إلى الحاجة اللي عم تحاولي تلبيها.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'NEED_NAME_001',requiresUserConfirmation:false,sources:[S.WHO_SELF_HELP_2026,S.ACT_FLEX_2024]}),
  card({code:'REQUEST_DIRECT_001',status:'active',titleAr:'طلب مباشر بدون لوم',shortDescriptionAr:'طلب سلوك محدد بدل النقد أو قراءة النوايا.',framework:'assertiveness / interpersonal effectiveness',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['connection','respect','support'],targetPatterns:['unmet_need','conflict_cycle','people_pleasing'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['needs','relationship'],exclusions:dangerBoundary,contraindicationNotesAr:'إذا في خوف من عنف أو انتقام أو إكراه، ما منستخدم مواجهة مباشرة كحل.',durationMin:5,stepsAr:['اذكري الحدث بدون حكم.','قولي تجربتك أو شعورك باختصار.','سمّي الحاجة.','اطلبي سلوك محدد وقابل للقبول أو الرفض.'],actionTemplateAr:'حوّلي حاجتك لطلب واحد محدد بدون اتهام.',measurementSpec:{before:['clarity_before'],after:['clarity_after'],outcome:['behavior_completed','real_world_result']},followUpSpec:follow('after_event','شو صار لما طلبتي بشكل مباشر؟'),fallbackCode:'NEED_NAME_001',requiresUserConfirmation:false,sources:[S.ASSERT_2026,S.COUPLES_META]}),
  card({code:'BOUNDARY_001',status:'active',titleAr:'حد واضح وقصير',shortDescriptionAr:'تحديد ما تقبلينه وما لا تقبلينه بدون تبرير طويل.',framework:'assertiveness / boundaries',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['boundary','autonomy','respect'],targetPatterns:['people_pleasing','control_overdrive','conflict_cycle'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['needs'],exclusions:dangerBoundary,contraindicationNotesAr:'الحد مو بديل عن خطة أمان إذا الطرف الآخر خطير.',durationMin:5,stepsAr:['حددي السلوك المقبول وغير المقبول بالنسبة إلك.','صيغي جملة قصيرة وواضحة.','ما تدخلي بتبرير لا ينتهي.'],actionTemplateAr:'اكتبي جملة حد قصيرة تقدري تلتزمي فيها.',measurementSpec:{before:['urge_before'],after:['urge_after'],outcome:['behavior_completed','real_world_result']},followUpSpec:follow('after_event','قدرتي تحافظي على الحد؟ شو صار بعدها؟'),fallbackCode:'NEED_NAME_001',requiresUserConfirmation:false,sources:[S.ASSERT_2026]}),
  card({code:'NO_TOLERATE_002',status:'active',titleAr:'أتحمل انزعاج كلمة لا',shortDescriptionAr:'البقاء مع الشعور بالذنب أو عدم رضا الآخر بدون سحب حد معقول فورًا.',framework:'assertiveness / psychological flexibility',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['boundary','autonomy','respect'],targetPatterns:['people_pleasing'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['needs'],exclusions:['Do not use to ignore evidence that the boundary itself was harmful or unfair.'],contraindicationNotesAr:'بنراجع الحد إذا كان مؤذي أو غير عادل، مو بس لأن وجود الذنب مزعج.',durationMin:8,stepsAr:['لاحظي الذنب أو القلق بعد قول لا.','اسألي إذا الحد نفسه معقول أو إذا بس رد فعل الآخر مزعج.','إذا الحد معقول، خلي الشعور يمر بدون اعتذار تلقائي أو سحب الحد.'],actionTemplateAr:'خلي انزعاج ما بعد “لا” موجود شوي بدون ما تلغي حَدّك فورًا.',measurementSpec:basicMeasure('urge'),followUpSpec:follow('after_event'),fallbackCode:'BOUNDARY_001',requiresUserConfirmation:false,sources:[S.ASSERT_2026,S.ACT_FLEX_2024]}),

  card({code:'UNCERTAINTY_001',status:'active',titleAr:'تحمّل جزء من عدم اليقين',shortDescriptionAr:'إيقاف الفحص المتكرر لفترة قصيرة مع إبقاء التواصل المناسب ممكنًا.',framework:'CBT / uncertainty tolerance',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['connection','clarity','regulation'],targetPatterns:['attachment_alarm','reassurance_loop','rumination'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['attachment','overthinking'],exclusions:['Not when credible immediate danger requires fact-finding or safety action.'],contraindicationNotesAr:'إذا في دليل خطر فعلي أو سبب واقعي للتحقق، مننتقل للفعل/الأمان بدل تدريب عدم اليقين.',durationMin:10,stepsAr:['سمّي الشي اللي ما بتعرفيه هلق.','اختاري فترة قصيرة بدون فحص أو طمأنة متكررة.','ارجعي لنشاط مهم خلال الفترة.','بعدها قرري إذا في تواصل مباشر واحد مطلوب.'],actionTemplateAr:'جربي 10–15 دقيقة بدون فحص متكرر، وبعدها قرري خطوة واحدة.',measurementSpec:{before:['urge_before'],after:['urge_after'],outcome:['checking_count','reassurance_count','recovery_minutes']},followUpSpec:follow('later_today'),fallbackCode:'RUMINATION_EXIT_001',requiresUserConfirmation:false,sources:[S.IU_2023,S.IU_2024]}),
  card({code:'ATT_TRIGGER_001',status:'active',titleAr:'خريطة تفعيل التعلق',shortDescriptionAr:'فهم المحفّز والخوف والسلوك بدون تحويل التعلق لهوية ثابتة.',framework:'attachment-informed coaching',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['connection','understanding'],targetPatterns:['attachment_alarm','reassurance_loop'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['attachment'],exclusions:['Attachment pattern is not a diagnosis or fixed personality label.'],contraindicationNotesAr:'إذا العلاقة فعليًا غير آمنة أو غير موثوقة، ما منفسر كل الإنذار كأنه داخلي.',durationMin:7,stepsAr:['شو اللي صار قبل الإنذار؟','شو الخوف اللي طلع؟','شو السلوك اللي حسّيتي بدك تعمليه؟','شو الحاجة اللي بدك توصلي إلها؟'],actionTemplateAr:'اعملي خريطة: محفّز → خوف → سلوك → حاجة.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'EMO_CHAIN_002',requiresUserConfirmation:false,sources:[S.ATTACH_2022]}),
  card({code:'ATT_REALITY_002',status:'active',titleAr:'إنذار داخلي أم دليل بالعلاقة؟',shortDescriptionAr:'فصل حساسية التعلق عن السلوك الخارجي الحقيقي.',framework:'attachment-informed reality testing',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['clarity','connection','respect'],targetPatterns:['attachment_alarm'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['attachment','relationship'],exclusions:['Never use to dismiss coercion, violence, deception, or repeated objective unreliability.'],contraindicationNotesAr:'إذا في تهديد/عنف/إكراه أو نمط موثّق من عدم الأمان، الأولوية للواقع والأمان.',durationMin:7,stepsAr:['اكتبي إشارات الإنذار اللي بجسمك وعقلك.','اكتبي السلوك الخارجي القابل للملاحظة.','اسألي شو معروف وشو مجهول.','اختاري استجابة تناسب الأدلة مو الخوف وحده.'],actionTemplateAr:'فرّقي بين اللي جسمك عم يحذرك منه وبين الدليل الخارجي الموجود فعلًا.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('later_today'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:false,sources:[S.ATTACH_2022,S.SAMHSA_TRAUMA]}),
  card({code:'ATT_REASSURE_DELAY_003',status:'active',titleAr:'تأجيل الطمأنة المتكررة',shortDescriptionAr:'إبطاء طلب الطمأنة أو الفحص المتكرر مع الحفاظ على تواصل طبيعي.',framework:'attachment-informed behavior change / uncertainty tolerance',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['connection','regulation'],targetPatterns:['reassurance_loop','attachment_alarm'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['attachment'],exclusions:['Not for situations where a practical response is legitimately overdue or safety information is needed.'],contraindicationNotesAr:'الهدف مو منع التواصل؛ الهدف كسر التكرار اللي يعطي راحة دقائق ويرجع الخوف.',durationMin:12,stepsAr:['لاحظي رغبة الفحص أو السؤال المتكرر.','نظّمي الشدة شوي.','حددي فترة تأجيل قصيرة.','إذا بقي في حاجة تواصل، اعملي تواصل واحد واضح.'],actionTemplateAr:'أجّلي الفحص/الطمأنة شوي ثم اختاري تواصل واحد إذا لزم.',measurementSpec:{before:['urge_before'],after:['urge_after'],outcome:['checking_count','reassurance_count']},followUpSpec:follow('later_today'),fallbackCode:'UNCERTAINTY_001',requiresUserConfirmation:false,sources:[S.IU_2023,S.RNT_2025]}),
  card({code:'ATT_REPAIR_004',status:'draft',titleAr:'رجوع بعد الخلاف بدون مطاردة أو انسحاب',shortDescriptionAr:'تهيئة خطوة إصلاح واضحة بعد ما تنخفض الشدة.',framework:'attachment-informed relationship coaching',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['connection','respect'],targetPatterns:['attachment_alarm','conflict_cycle'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['attachment','relationship'],exclusions:dangerBoundary,contraindicationNotesAr:'يحتاج مراجعة حدود سريرية/علاقية قبل التفعيل العام. لا يستخدم في علاقة غير آمنة.',durationMin:8,stepsAr:['تأكدي إن الشدة نزلت.','حددي شو بدك تصلحيه تحديدًا.','عبري عن مسؤوليتك أو حاجتك بدون مطاردة/تهديد.','اطلبي رجعة للحوار بوقت مناسب.'],actionTemplateAr:'حضّري جملة إصلاح واحدة وموعد رجوع للحوار.',measurementSpec:{outcome:['behavior_completed','real_world_result','recovery_minutes']},followUpSpec:follow('after_event'),fallbackCode:'REQUEST_DIRECT_001',requiresUserConfirmation:true,sources:[S.COUPLES_META,S.ATTACH_2022]}),

  card({code:'REL_CYCLE_001',status:'draft',titleAr:'دائرة الخلاف بدل مين الغلطان',shortDescriptionAr:'رسم تسلسل تفاعل الطرفين لفهم الحلقة المتكررة.',framework:'couple-therapy-informed coaching',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['clarity','connection'],targetPatterns:['conflict_cycle'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['relationship'],exclusions:dangerBoundary,contraindicationNotesAr:'لا نستخدم “الدائرة” لمعادلة المسؤولية بين عنف/إكراه وبين رد فعل الطرف المتضرر.',durationMin:10,stepsAr:['شو عمل الطرف الأول؟','شو فهم الطرف الثاني وعمل؟','كيف رجع هذا السلوك أثّر على الأول؟','وين أصغر نقطة ممكن نكسر فيها الحلقة؟'],actionTemplateAr:'ارسمي دائرة الخلاف كسلوك → رد → رد، بدون شتائم أو تشخيص.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'EMO_CHAIN_002',requiresUserConfirmation:true,sources:[S.COUPLES_META,S.IBCT_REVIEW]}),
  card({code:'ANGER_TIMEOUT_001',status:'active',titleAr:'توقف آمن مع موعد رجوع',shortDescriptionAr:'توقف غير عقابي أثناء التصعيد مع اتفاق رجوع واضح.',framework:'anger management / interpersonal effectiveness',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['regulation','respect'],targetPatterns:['anger_escalation','conflict_cycle'],eligibleStates:['high_activation','moderate_activation'],journeyDomains:['anger','relationship'],exclusions:['Not a silent-treatment punishment.','Not for immediate violence risk; use safety mode.'],contraindicationNotesAr:'إذا في احتمال أذى مباشر، مننتقل للأمان وما منكتفي بتقنية timeout.',durationMin:20,stepsAr:['قولي إن الشدة عالية ولازم توقف مؤقت.','حددي وقت رجوع واضح إذا الوضع آمن.','استخدمي الوقت للتنظيم، مو لتجميع حجج جديدة.'],actionTemplateAr:'وقفي الحوار مؤقتًا وحددي موعد رجوع واضح.',measurementSpec:{before:['intensity_before'],after:['intensity_after'],outcome:['behavior_completed','recovery_minutes']},followUpSpec:follow('after_event'),fallbackCode:'REG_GROUND_001',requiresUserConfirmation:false,sources:[S.ANGER_META,S.COUPLES_META]}),
  card({code:'REL_SOFT_START_002',status:'draft',titleAr:'بداية هادئة لموضوع صعب',shortDescriptionAr:'بدء الحوار بوصف الموقف والحاجة بدل الاتهام الشامل.',framework:'couple-therapy-informed assertiveness',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['connection','respect'],targetPatterns:['conflict_cycle'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['relationship'],exclusions:dangerBoundary,contraindicationNotesAr:'لا تُستخدم لمواجهة شخص قد يعاقب أو يؤذي بسبب التعبير.',durationMin:7,stepsAr:['حددي موضوع واحد.','ابدئي بما حدث بدل “أنت دائمًا”.','قولي أثره عليك وحاجتك.','اطلبي خطوة قابلة للنقاش.'],actionTemplateAr:'حضّري أول جملتين من الحوار بدون اتهام شامل.',measurementSpec:{outcome:['behavior_completed','real_world_result']},followUpSpec:follow('after_event'),fallbackCode:'REQUEST_DIRECT_001',requiresUserConfirmation:true,sources:[S.COUPLES_META,S.ASSERT_2026]}),
  card({code:'REL_REPAIR_003',status:'draft',titleAr:'إصلاح بعد الخلاف',shortDescriptionAr:'مسؤولية محددة + أثر + خطوة إصلاح بدل اعتذار فارغ.',framework:'couple-therapy-informed repair',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['connection','respect'],targetPatterns:['conflict_cycle'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['relationship'],exclusions:dangerBoundary,contraindicationNotesAr:'الإصلاح لا يعني الضغط على الطرف المتضرر للمسامحة ولا يسقط الحاجة للأمان أو الحدود.',durationMin:10,stepsAr:['سمّي السلوك اللي تتحملي مسؤوليته.','اعترفي بالأثر بدون “بس”.','قولي شو رح تعملي بشكل مختلف.','اسألي إذا في خطوة إصلاح مناسبة للطرفين.'],actionTemplateAr:'اعملي إصلاح محدد: مسؤولية + أثر + تغيير.',measurementSpec:{outcome:['behavior_completed','real_world_result','recovery_minutes']},followUpSpec:follow('after_event'),fallbackCode:'REQUEST_DIRECT_001',requiresUserConfirmation:true,sources:[S.COUPLES_META,S.IBCT_REVIEW]}),
  card({code:'REL_TRUST_STEP_004',status:'draft',titleAr:'الثقة بخطوات قابلة للملاحظة',shortDescriptionAr:'بناء الثقة من الاتساق والسلوك بدل إجبار النفس على ثقة عمياء.',framework:'relationship coaching / behavioral consistency',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['connection','respect','clarity'],targetPatterns:['conflict_cycle','attachment_alarm'],eligibleStates:['reflective'],journeyDomains:['relationship','healing'],exclusions:['Do not use to pressure reconciliation after betrayal or abuse.'],contraindicationNotesAr:'الثقة اختيار تدريجي مبني على سلوك؛ مو واجب، وخصوصًا بعد خيانة أو أذى.',durationMin:10,stepsAr:['حددي السلوك اللي يحتاج يصير موثوق.','شو دليل الاتساق اللي ممكن ينشاف مع الوقت؟','شو حدّك إذا الاتساق ما صار؟','راجعي الأدلة بعد فترة بدل قرار ثقة شامل الآن.'],actionTemplateAr:'اختاري معيار ثقة سلوكي واحد تراقبيه عبر الوقت.',measurementSpec:{outcome:['real_world_result'],after:['clarity_after']},followUpSpec:follow('tomorrow'),fallbackCode:'ATT_REALITY_002',requiresUserConfirmation:true,sources:[S.COUPLES_META,S.IBCT_REVIEW]}),

  card({code:'THOUGHT_FACTS_001',status:'active',titleAr:'الحدث أم التفسير؟',shortDescriptionAr:'فصل ما حصل فعليًا عما أضافه العقل من معنى.',framework:'CBT cognitive restructuring',evidenceTier:'A',contentOrigin:'original_malaak',targetNeeds:['understanding','clarity'],targetPatterns:['thought_fusion','attachment_alarm','conflict_cycle','unknown'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['overthinking'],exclusions:['Avoid repetitive debate when reassurance/obsessional loop is primary.'],contraindicationNotesAr:'إذا عم نعيد نفس السؤال بدون معلومة جديدة، منوقف المناقشة وننتقل للخروج من الحلقة.',durationMin:6,stepsAr:['اكتبي حقيقة ممكن الكاميرا تسجلها.','اكتبي تفسير عقلك.','اكتبي معلومة ما زالت مجهولة.','اختاري تفسير متوازن ما يحتاج يقين مزيف.'],actionTemplateAr:'افصلي بين حقيقة واحدة وتفسير واحد وشي مجهول.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('later_today'),fallbackCode:'RUMINATION_EXIT_001',requiresUserConfirmation:false,sources:[S.NICE_GAD,S.RNT_2025]}),
  card({code:'RUMINATION_EXIT_001',status:'active',titleAr:'الخروج من الحلقة',shortDescriptionAr:'إيقاف جولة التحليل لما ما عاد تنتج معلومة أو قرار.',framework:'CBT / metacognitive disengagement',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['regulation','clarity'],targetPatterns:['rumination','reassurance_loop'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['overthinking'],exclusions:['Do not use to suppress actionable safety information.'],contraindicationNotesAr:'إذا في معلومة أمنية/عملية جديدة، نتصرف عليها بدل إغلاق التفكير.',durationMin:4,stepsAr:['اسألي: ظهر شي جديد؟','إذا لا، سمّي إنك داخل الحلقة.','وقفي الجولة الحالية.','ارجعي لنشاط محدد 10 دقايق.'],actionTemplateAr:'وقفي جولة التحليل وارجعي لنشاط محدد 10 دقائق.',measurementSpec:{before:['urge_before'],after:['urge_after'],outcome:['recovery_minutes']},followUpSpec:follow('later_today'),fallbackCode:'REG_GROUND_001',requiresUserConfirmation:false,sources:[S.RNT_2025]}),
  card({code:'PROBLEM_SOLVE_001',status:'active',titleAr:'مشكلة واحدة وخطوة واحدة',shortDescriptionAr:'تحويل التفكير المفيد إلى فعل صغير قابل للتنفيذ.',framework:'CBT problem solving',evidenceTier:'A',contentOrigin:'original_malaak',targetNeeds:['decision','clarity','autonomy'],targetPatterns:['practical_problem','control_overdrive','unknown'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['inner-peace','overthinking'],exclusions:['Not for immediate danger requiring safety action.'],contraindicationNotesAr:'إذا المشكلة مو قابلة للحل الآن، مننتقل لتحمل عدم اليقين أو القبول بدل المزيد من التخطيط.',durationMin:8,stepsAr:['عرّفي المشكلة بجملة قابلة للحل.','افصلي شو بإيدك.','اختاري أصغر خطوة.','حددي متى تنفذيها.'],actionTemplateAr:'اختاري مشكلة وحدة تحت سيطرتك ونفذي أصغر خطوة.',measurementSpec:{before:['clarity_before'],after:['clarity_after'],outcome:['behavior_completed','real_world_result']},followUpSpec:follow('after_event'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:false,sources:[S.NICE_GAD]}),
  card({code:'WORRY_POSTPONE_002',status:'active',titleAr:'أجّلي القلق لوقت محدد',shortDescriptionAr:'تأجيل القلق غير العاجل بدل الاستجابة له طول اليوم.',framework:'CBT worry management',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['clarity','regulation'],targetPatterns:['rumination'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['overthinking'],exclusions:['Do not postpone urgent safety or practical action.'],contraindicationNotesAr:'المقصود قلق متكرر غير عاجل، مو مهمة ضرورية أو خطر فعلي.',durationMin:5,stepsAr:['اكتبي عنوان القلق بكلمتين.','حددي وقت قصير لاحق اليوم للرجوع له.','لما يرجع، ذكري حالك إنه محفوظ لوقته.','ارجعي للي عم تعمليه الآن.'],actionTemplateAr:'احفظي القلق لوقت محدد لاحقًا وارجعي لمهمتك الحالية.',measurementSpec:{outcome:['recovery_minutes'],before:['urge_before'],after:['urge_after']},followUpSpec:follow('later_today','لما وصل وقت القلق، بقي بنفس القوة ولا تغيّر؟'),fallbackCode:'RUMINATION_EXIT_001',requiresUserConfirmation:false,sources:[S.RNT_2025,S.NICE_GAD]}),
  card({code:'DEFUSION_003',status:'active',titleAr:'هاي فكرة مو أمر',shortDescriptionAr:'ملاحظة الفكرة كحدث ذهني بدل التعامل معها كحقيقة أو أمر للتصرف.',framework:'ACT cognitive defusion',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['clarity','regulation'],targetPatterns:['thought_fusion','rumination'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['overthinking'],exclusions:['Not a substitute for evaluating credible external danger or factual evidence.'],contraindicationNotesAr:'إذا الفكرة تنبه لخطر فعلي، لازم نفحص الواقع بدل نعتبرها مجرد ذهن.',durationMin:4,stepsAr:['قولي: “عم لاحظ فكرة إن…” بدل “أكيد…”.','لاحظي الشعور اللي بيجي معها.','اختاري إذا بدك تتصرفي حسب قيمك رغم وجود الفكرة.'],actionTemplateAr:'صيغيها: “عم لاحظ فكرة إن…” وخدي خطوة حسب قيمك مو حسب الخوف وحده.',measurementSpec:basicMeasure('urge'),followUpSpec:follow('later_today'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:false,sources:[S.ACT_FLEX_2024,S.WHO_DWM]}),
  card({code:'REASSURANCE_BREAK_004',status:'active',titleAr:'هل الجواب عم يريحني خمس دقايق بس؟',shortDescriptionAr:'كشف تكرار طلب نفس الجواب لما الطمأنة قصيرة العمر.',framework:'CBT / repetitive negative thinking management',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['regulation','clarity'],targetPatterns:['reassurance_loop','rumination'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['overthinking','attachment'],exclusions:['Do not block appropriate one-time clarification or needed safety information.'],contraindicationNotesAr:'مو كل سؤال طمأنة مشكلة؛ الهدف التكرار اللي ما بيضيف معلومة.',durationMin:5,stepsAr:['عدّي كم مرة رجع نفس السؤال.','اسألي شو مدة الراحة بعد آخر جواب.','إذا كانت قصيرة ورجع السؤال، سمي الحلقة.','اختاري أداة تحمل عدم اليقين أو الخروج من الحلقة.'],actionTemplateAr:'وقفي جواب جديد لنفس السؤال وجربي تحمل عدم اليقين شوي.',measurementSpec:{outcome:['reassurance_count','checking_count'],before:['urge_before'],after:['urge_after']},followUpSpec:follow('later_today'),fallbackCode:'UNCERTAINTY_001',requiresUserConfirmation:false,sources:[S.RNT_2025,S.IU_2023]}),

  card({code:'ANGER_THERMOMETER_002',status:'active',titleAr:'مقياس غضبي المبكر',shortDescriptionAr:'اكتشاف علامات 3–6/10 قبل الوصول للانفجار.',framework:'anger self-monitoring',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['regulation','clarity'],targetPatterns:['anger_escalation'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['anger'],exclusions:['Not a violence-risk assessment.'],contraindicationNotesAr:'إذا في خوف من أذى مباشر، رقم الغضب ما بكفي وننتقل لمسار الأمان.',durationMin:6,stepsAr:['شو أول علامة بجسمك؟','شو أول فكرة؟','شو أول رغبة سلوكية؟','حددي مستوى تقريبي لازم عنده توقفي وتستخدمي مهارة.'],actionTemplateAr:'حددي 3 إشارات بتقول إن غضبك عم يطلع قبل الانفجار.',measurementSpec:{before:['intensity_before'],outcome:['recovery_minutes']},followUpSpec:follow('tomorrow'),fallbackCode:'REG_GROUND_001',requiresUserConfirmation:false,sources:[S.ANGER_META,S.GROSS_ER]}),
  card({code:'ANGER_CHAIN_003',status:'active',titleAr:'سلسلة الغضب كاملة',shortDescriptionAr:'ربط عوامل الضعف والمحفز والتفسير والرغبة والسلوك والنتيجة.',framework:'CBT anger chain analysis',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['understanding','clarity'],targetPatterns:['anger_escalation'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['anger'],exclusions:['Do not use chain analysis instead of immediate safety action when violence is imminent.'],contraindicationNotesAr:'نحلل بعد الأمان، مو أثناء خطر مباشر.',durationMin:10,stepsAr:['شو كان وضعك قبل الموقف: نوم/تعب/حمل؟','شو المحفز؟','شو معنى الموقف بعقلك؟','شو الرغبة والسلوك؟','شو النتيجة القصيرة والطويلة؟'],actionTemplateAr:'ارسمي سلسلة الغضب وحددي أول نقطة ممكن تغيّريها.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'EMO_CHAIN_002',requiresUserConfirmation:false,sources:[S.ANGER_META,S.GROSS_ER]}),
  card({code:'ANGER_ASSERT_004',status:'draft',titleAr:'حوّلي رسالة الغضب لحزم',shortDescriptionAr:'استخدام معلومة الغضب لطلب أو حد واضح بدل عدوان أو كبت.',framework:'anger management / assertiveness',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['respect','boundary','clarity'],targetPatterns:['anger_escalation','conflict_cycle'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['anger'],exclusions:dangerBoundary,contraindicationNotesAr:'الحزم بعد ما تنخفض الشدة فقط، وفي الأمان فقط.',durationMin:8,stepsAr:['شو الرسالة المفيدة بالغضب؟','هل هي حاجة، حد، ظلم، أو حمل زائد؟','حوّليها لجملة حازمة بدون تهديد.'],actionTemplateAr:'حوّلي معلومة الغضب لطلب أو حد واحد واضح.',measurementSpec:{outcome:['behavior_completed','real_world_result']},followUpSpec:follow('after_event'),fallbackCode:'BOUNDARY_001',requiresUserConfirmation:true,sources:[S.ANGER_META,S.ASSERT_2026]}),
  card({code:'ANGER_REPAIR_005',status:'draft',titleAr:'إصلاح بعد سلوك مؤذي',shortDescriptionAr:'تحمّل المسؤولية وإصلاح ما يمكن بدون هروب للعار.',framework:'anger management / accountability coaching',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['respect','connection'],targetPatterns:['anger_escalation'],eligibleStates:['reflective'],journeyDomains:['anger','relationship'],exclusions:['Not a substitute for safeguarding after violence or child harm.'],contraindicationNotesAr:'إذا صار أذى جسدي أو تكرر فقد السيطرة، لازم تقييم ودعم بشري مناسب؛ الاعتذار وحده مو خطة أمان.',durationMin:10,stepsAr:['سمّي شو عملتي بدون تبرير.','تأكدي من سلامة الشخص المتأذي.','اعتذري عن السلوك المحدد إذا مناسب.','اعملي خطوة تمنع التكرار واطلبي دعم إذا فقد السيطرة عم يتكرر.'],actionTemplateAr:'تحمّلي مسؤولية السلوك واعملِي خطوة إصلاح ومنع تكرار.',measurementSpec:{outcome:['behavior_completed','real_world_result']},followUpSpec:follow('after_event'),fallbackCode:'ANGER_CHAIN_003',requiresUserConfirmation:true,requiresHumanSupport:true,sources:[S.ANGER_META,S.SAMHSA_TRAUMA]}),

  card({code:'CHILD_PRESENT_PAST_001',status:'draft',titleAr:'الماضي لمس الحاضر، بس الحاضر مو الماضي',shortDescriptionAr:'تمييز التشابه بين محفز حالي وتعلّم قديم بدون افتراض قصة مخفية.',framework:'schema-informed present-focused coaching',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['clarity','regulation'],targetPatterns:['thought_fusion','people_pleasing','attachment_alarm'],eligibleStates:['reflective'],journeyDomains:['childhood'],exclusions:traumaBoundary,contraindicationNotesAr:'ممنوع استخدامه لاسترجاع ذاكرة مخفية أو إعادة عيش صدمة. إذا ظهرت أعراض صدمية شديدة، نوقف ونوجّه لدعم متخصص.',durationMin:8,stepsAr:['شو الموقف الحالي فعلًا؟','شو الإحساس أو القاعدة القديمة اللي تشبهه؟','شو الاختلاف بين وقتها وهلأ؟','شو قدرة أو خيار عندك اليوم ما كان موجود قبل؟'],actionTemplateAr:'اكتبي فرقين بين الماضي والحاضر قبل ما تتصرفي كأنهم نفس الشي.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:true,sources:[S.SAMHSA_TRAUMA,S.CHILD_SELF_COMP]}),
  card({code:'CHILD_OLD_BELIEF_002',status:'draft',titleAr:'معتقد قديم مو حقيقة نهائية',shortDescriptionAr:'صياغة قاعدة قديمة كفرضية تعلّمتها، لا كحقيقة أو ذاكرة مؤكدة.',framework:'schema-informed cognitive coaching',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['clarity','understanding'],targetPatterns:['people_pleasing','thought_fusion','attachment_alarm'],eligibleStates:['reflective'],journeyDomains:['childhood'],exclusions:traumaBoundary,contraindicationNotesAr:'لا نسأل “شو لازم يكون صار؟” ولا نختلق أسباب طفولة. نشتغل فقط على الاعتقاد اللي المستخدم يلاحظ وجوده الآن.',durationMin:9,stepsAr:['اكتبي القاعدة اللي بتطلع اليوم: مثل “لازم أرضي الكل”.','قولي: “يمكن تعلمت هالقاعدة بوقت سابق”.','اجمعي دليل من الحاضر معها وضدها.','اختاري قاعدة أوسع وأكثر مرونة.'],actionTemplateAr:'حوّلي القاعدة القديمة لفرضية قابلة للفحص بالحاضر.',measurementSpec:basicMeasure('belief'),followUpSpec:follow('tomorrow'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:true,sources:[S.SAMHSA_TRAUMA,S.CHILD_SELF_COMP]}),
  card({code:'CHILD_SELF_COMPASSION_003',status:'draft',titleAr:'رحمة بالنفس مع مسؤولية اليوم',shortDescriptionAr:'التعامل بلطف مع أثر التجربة القديمة بدون إعفاء السلوك الحالي من المسؤولية.',framework:'self-compassion / trauma-informed coaching',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['support','regulation'],targetPatterns:['people_pleasing','anger_escalation','thought_fusion'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['childhood'],exclusions:traumaBoundary,contraindicationNotesAr:'الرحمة بالنفس ما تعني تبرير إيذاء الآخرين أو تفادي الإصلاح.',durationMin:7,stepsAr:['سمّي اللي كان صعب عليك بدون جلد ذات.','قولي شو بتحتاجي تسمعيه بطريقة واقعية ولطيفة.','اسألي شو مسؤوليتك اليوم رغم فهم السبب.'],actionTemplateAr:'اكتبي جملة رحيمة وجملة مسؤولية لنفس الموقف.',measurementSpec:basicMeasure('intensity'),followUpSpec:follow('tomorrow'),fallbackCode:'EMO_NAME_001',requiresUserConfirmation:true,sources:[S.SELF_COMP_2023,S.CHILD_SELF_COMP,S.SAMHSA_TRAUMA]}),
  card({code:'CHILD_PATTERN_EXPERIMENT_004',status:'draft',titleAr:'جرّبي عكس القاعدة القديمة بخطوة صغيرة',shortDescriptionAr:'تجربة سلوكية منخفضة المخاطر لاختبار قاعدة قديمة بالحاضر.',framework:'CBT behavioral experiment / schema-informed coaching',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['autonomy','boundary','clarity'],targetPatterns:['people_pleasing','control_overdrive','thought_fusion'],eligibleStates:['reflective'],journeyDomains:['childhood'],exclusions:[...traumaBoundary,'Only low-risk present-day behavioral experiments; never exposure to traumatic memories.'],contraindicationNotesAr:'التجربة تكون بالحاضر وبموقف آمن وقابل للتراجع، مو مواجهة خطر أو صدمة.',durationMin:12,stepsAr:['سمّي القاعدة القديمة وتوقعها.','اختاري خطوة صغيرة آمنة بعكسها.','اكتبي شو بتتوقعي يصير.','اعملي التجربة وسجلي شو صار فعلًا.'],actionTemplateAr:'اختاري تجربة صغيرة آمنة تختبر قاعدة قديمة بالحاضر.',measurementSpec:{before:['belief_before'],after:['belief_after'],outcome:['behavior_completed','real_world_result']},followUpSpec:follow('after_event'),fallbackCode:'BOUNDARY_001',requiresUserConfirmation:true,sources:[S.NICE_GAD,S.SAMHSA_TRAUMA]}),

  card({code:'HEAL_STABILIZE_001',status:'draft',titleAr:'ثبّت حياتك قبل تحليل القصة',shortDescriptionAr:'حماية النوم/الوظائف اليومية وتقليل الاندفاع قبل تحليل جرح عاطفي.',framework:'trauma-informed stabilization coaching',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['regulation','rest','support'],targetPatterns:['rumination','attachment_alarm','anger_escalation'],eligibleStates:['high_activation','moderate_activation'],journeyDomains:['healing'],exclusions:traumaBoundary,contraindicationNotesAr:'إذا في PTSD محتمل شديد، تفكك، إيذاء نفس، أو تعطّل كبير، ما منفتح معالجة ذاتية عميقة ونوصي بتقييم متخصص.',durationMin:8,stepsAr:['شو الوظيفة الأساسية اللي عم تنهار: نوم/أكل/شغل/أطفال؟','اختاري حماية واحدة لليوم.','خففي محفز ذاتي واحد مثل مراقبة مستمرة.','حددي شخص دعم أو مساعدة عملية إذا متاحة.'],actionTemplateAr:'احمي وظيفة أساسية اليوم قبل أي تحليل إضافي.',measurementSpec:{outcome:['behavior_completed','recovery_minutes'],before:['intensity_before'],after:['intensity_after']},followUpSpec:follow('tomorrow'),fallbackCode:'REST_RECOVERY_001',requiresUserConfirmation:true,requiresHumanSupport:false,sources:[S.SAMHSA_TRAUMA,S.WHO_SELF_HELP_2026]}),
  card({code:'HEAL_FACTS_STORY_002',status:'draft',titleAr:'شو صار وشو قصتي عنه',shortDescriptionAr:'فصل الوقائع والتفسير والمسؤوليات والمجهول بعد جرح عاطفي.',framework:'CBT-informed relational injury reflection',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['clarity','respect'],targetPatterns:['rumination','thought_fusion'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['healing'],exclusions:traumaBoundary,contraindicationNotesAr:'مو جلسة كشف حقيقة مخفية ولا تحقيق قهري؛ إذا المعلومات غير متاحة، منترك “المجهول” موجود.',durationMin:10,stepsAr:['شو الوقائع المعروفة؟','شو تفسيرك؟','شو مسؤوليتك الفعلية؟','شو مسؤولية الطرف الآخر؟','شو ما زال مجهول؟'],actionTemplateAr:'رتّبي القصة لخمس خانات: حقيقة/تفسير/مسؤوليتي/مسؤوليته/مجهول.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:true,sources:[S.NICE_GAD,S.SAMHSA_TRAUMA]}),
  card({code:'HEAL_GRIEF_003',status:'draft',titleAr:'شو خسرت فعلًا؟',shortDescriptionAr:'تحديد أوجه الخسارة بدون فرض مراحل حزن ثابتة أو إجبار على النسيان.',framework:'grief-informed coaching',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['understanding','support'],targetPatterns:['rumination','attachment_alarm'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['healing'],exclusions:[...traumaBoundary,'Not a treatment protocol for prolonged grief disorder.'],contraindicationNotesAr:'إذا الحزن شديد ومستمر ومُعطّل بشكل كبير، نوصي بتقييم مختص بدل زيادة تمارين ذاتية.',durationMin:10,stepsAr:['اكتبي شو خسرتي غير الشخص نفسه: مستقبل/روتين/هوية/أمان/مجتمع.','اختاري أكثر خسارة مؤلمة اليوم.','اسألي شو تحتاج هاي الخسارة: وقت/دعم/قرار/تغيير روتين.'],actionTemplateAr:'سمّي أكثر شي خسرتيه فعلًا بدل اختصار كل الألم بـ“اشتقتله”.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'EMO_NAME_001',requiresUserConfirmation:true,sources:[S.GRIEF_2024]}),
  card({code:'HEAL_SELF_WORTH_004',status:'draft',titleAr:'قرار شخص مو مقياس لقيمتي',shortDescriptionAr:'فصل الرفض/الخيانة/الانفصال عن حكم شامل على قيمة الذات.',framework:'CBT / self-compassion informed coaching',evidenceTier:'B',contentOrigin:'original_malaak',targetNeeds:['respect','support','clarity'],targetPatterns:['thought_fusion','attachment_alarm'],eligibleStates:['reflective','moderate_activation'],journeyDomains:['healing'],exclusions:traumaBoundary,contraindicationNotesAr:'نقدر نتعلم من أخطائنا بالعلاقة بدون تحويل قرار شخص آخر لقياس لقيمتنا الإنسانية.',durationMin:8,stepsAr:['اكتبي الحدث.','اكتبي الحكم اللي صار على قيمتك.','شو أشياء ممكن نتعلم منها فعلًا؟','شو أجزاء الحكم ما بيثبتها الحدث؟'],actionTemplateAr:'افصلي درس العلاقة عن حكم “أنا ما بنحب/مو كفاية”.',measurementSpec:{before:['belief_before'],after:['belief_after'],outcome:['clarity_after']},followUpSpec:follow('tomorrow'),fallbackCode:'THOUGHT_FACTS_001',requiresUserConfirmation:true,sources:[S.SELF_COMP_2023,S.NICE_GAD]}),
  card({code:'HEAL_TRUST_GRADUAL_005',status:'draft',titleAr:'ثقة متدرجة مو عمياء',shortDescriptionAr:'إعطاء الثقة بحسب السلوك والاتساق والزمن.',framework:'relationship/healing coaching',evidenceTier:'C',contentOrigin:'original_malaak',targetNeeds:['connection','respect','clarity'],targetPatterns:['attachment_alarm','conflict_cycle'],eligibleStates:['reflective'],journeyDomains:['healing','relationship'],exclusions:['Do not pressure reconciliation, forgiveness, or renewed trust after abuse or betrayal.','Not trauma processing or memory-recovery work.'],contraindicationNotesAr:'الثقة تُبنى حسب الأدلة؛ وإذا العلاقة غير آمنة فالهدف حماية النفس مو تدريب الثقة.',durationMin:10,stepsAr:['اختاري مجال ثقة واحد.','حددي السلوك اللي يثبت الاتساق.','حددي مدة مراجعة معقولة.','راجعي السلوك الفعلي بدل وعد عام.'],actionTemplateAr:'اختاري معيار ثقة واحد وخليه يُثبت بالسلوك عبر الوقت.',measurementSpec:{outcome:['real_world_result'],after:['clarity_after']},followUpSpec:follow('tomorrow'),fallbackCode:'ATT_REALITY_002',requiresUserConfirmation:true,sources:[S.COUPLES_META,S.SAMHSA_TRAUMA]}),

  card({code:'BAL_WAR_MODE_001',status:'active',titleAr:'هل أنا بوضع حرب؟',shortDescriptionAr:'تسمية حالة overdrive/دفاع ضمن نموذج Coaching بدون ادعاء أنها آلية أنثوية بيولوجية.',framework:'coaching_model / stress-overdrive reflection',evidenceTier:'D',contentOrigin:'coaching_only_original_malaak',targetNeeds:['clarity','rest','autonomy'],targetPatterns:['control_overdrive','anger_escalation'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['feminine-balance'],exclusions:['Do not present feminine/masculine energy as established biology or clinical construct.'],contraindicationNotesAr:'القوة والحزم مو مشكلة بحد ذاتهم؛ السؤال عن الجمود والاستنفار والتكلفة.',durationMin:6,stepsAr:['شو جسمك عم يعمل: شد/سرعة/استنفار؟','شو السلوك: سيطرة/نقد/استعجال/تحمل كل شي؟','هل الوضع فعلًا يحتاج قوة الآن ولا عادة الحرب اشتغلت؟'],actionTemplateAr:'سمّي سلوك حرب واحد شغال هلق ووقفيه إذا مو ضروري.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('later_today'),fallbackCode:'CONTROL_CIRCLE_001',requiresUserConfirmation:false,sources:[]}),
  card({code:'BAL_CONTROL_RESP_002',status:'active',titleAr:'سيطرة أم مسؤولية؟',shortDescriptionAr:'الحفاظ على المسؤولية مع ترك إدارة كل تفاصيل الآخرين.',framework:'coaching_model / problem-solving and flexibility',evidenceTier:'D',contentOrigin:'coaching_only_original_malaak',targetNeeds:['autonomy','clarity'],targetPatterns:['control_overdrive'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['feminine-balance'],exclusions:['Does not ask users to surrender legitimate responsibility or safety decisions.'],contraindicationNotesAr:'إذا المسؤولية قانونية/أبوية/مهنية فعلية، منحددها بوضوح وما منسميها سيطرة.',durationMin:7,stepsAr:['شو مسؤوليتك الفعلية؟','شو الجزء اللي عم تديري فيه شخص ثاني؟','شو نتيجة جيدة كفاية بدل الكمال؟','اتركي تفصيل واحد لغيرك مع حد واضح.'],actionTemplateAr:'اعملي مسؤوليتك واتركي تفصيل واحد مو لازم تتحكمي فيه.',measurementSpec:{outcome:['behavior_completed'],before:['urge_before'],after:['urge_after']},followUpSpec:follow('after_event'),fallbackCode:'CONTROL_CIRCLE_001',requiresUserConfirmation:false,sources:[S.PERFECTION_2021,S.ACT_FLEX_2024]}),
  card({code:'BAL_RECEIVE_REST_003',status:'active',titleAr:'استقبال وراحة بدون فقد الذات',shortDescriptionAr:'تجربة مساعدة/راحة صغيرة بدون تحويلها لاتكالية أو “أنوثة واجبة”.',framework:'coaching_model / recovery and receiving support',evidenceTier:'D',contentOrigin:'coaching_only_original_malaak',targetNeeds:['rest','support','connection'],targetPatterns:['control_overdrive'],eligibleStates:['moderate_activation','reflective','unknown'],journeyDomains:['feminine-balance'],exclusions:['Do not frame passivity, financial dependence, or surrender of rights as femininity.'],contraindicationNotesAr:'الاستقبال اختيار، والاستقلال والقدرة على الرفض بيضلوا موجودين.',durationMin:6,stepsAr:['اختاري مساعدة صغيرة آمنة ممكن تقبليها.','لاحظي إذا بيطلع ذنب/حاجة للرد فورًا.','اسمحي بالمساعدة بدون دين عاطفي تلقائي.'],actionTemplateAr:'اقبلي مساعدة صغيرة اليوم بدون ما ترجعي تدفعي ثمنها فورًا.',measurementSpec:{outcome:['behavior_completed'],before:['urge_before'],after:['urge_after']},followUpSpec:follow('after_event'),fallbackCode:'REST_RECOVERY_001',requiresUserConfirmation:false,sources:[]}),

  card({code:'FI_STATE_COMPASS_001',status:'active',titleAr:'شو الحالة اللي عم تقودني؟',shortDescriptionAr:'استخدام نموذج الحالات الأربع كعدسة Coaching سياقية لا كتشخيص أو هوية.',framework:'coaching_model / feminine-intelligence taxonomy',evidenceTier:'D',contentOrigin:'coaching_only_original_malaak',targetNeeds:['clarity','autonomy'],targetPatterns:['people_pleasing','control_overdrive','unknown'],eligibleStates:['reflective','moderate_activation','unknown'],journeyDomains:['feminine-intelligence'],exclusions:['Taxonomy is not a validated psychological construct; never show a percentage or fixed identity label.'],contraindicationNotesAr:'النتيجة “يميل سلوكك بهالسياق” فقط، وما منعتبر الذكاء الذكوري مشكلة لازم تختفي.',durationMin:7,stepsAr:['هل عم تفقدي نفسك لإرضاء الآخر؟','هل عم تحاولي تتحكمي بكل شي تحت ضغط؟','هل عم تستخدمي الحسم/الواقعية بمرونة؟','هل في قوة + حدود + مرونة + اتصال بالمشاعر؟'],actionTemplateAr:'سمّي الحالة الأقرب لهالموقف فقط، مو لشخصيتك كلها.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('tomorrow'),fallbackCode:'CONTROL_CIRCLE_001',requiresUserConfirmation:true,sources:[]}),
  card({code:'FI_TIME_DISTANCE_002',status:'active',titleAr:'الوقت والمسافة قبل الرد',shortDescriptionAr:'إضافة توقيت ومسافة منظورية قبل القرار ضمن نموذج البوصلة.',framework:'coaching_model / perspective and timing',evidenceTier:'D',contentOrigin:'coaching_only_original_malaak',targetNeeds:['clarity','decision'],targetPatterns:['anger_escalation','rumination','control_overdrive'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['feminine-intelligence'],exclusions:['Do not delay urgent safety, legal, medical, or time-sensitive action.'],contraindicationNotesAr:'المسافة مو انسحاب عقابي، والوقت مو تأجيل دائم للمشكلة.',durationMin:6,stepsAr:['هل لازم أتصرف هلق فعلًا؟','شو بيتغير لو شفت الموقف من أسبوع لقدام؟','شو المهم بعيدًا عن حرارة اللحظة؟'],actionTemplateAr:'اختاري إذا هاد وقت فعل أو وقت تهدئة وجمع منظور.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('later_today'),fallbackCode:'LOAD_SORT_001',requiresUserConfirmation:false,sources:[S.ACT_FLEX_2024]}),
  card({code:'FI_EMOTION_INTENTION_003',status:'active',titleAr:'المشاعر والنية',shortDescriptionAr:'اعتبار الشعور معلومة ثم توضيح الهدف الحقيقي قبل التصرف.',framework:'coaching_model / emotion-informed intentional action',evidenceTier:'D',contentOrigin:'coaching_only_original_malaak',targetNeeds:['clarity','decision','respect'],targetPatterns:['anger_escalation','people_pleasing','control_overdrive','unknown'],eligibleStates:['moderate_activation','reflective'],journeyDomains:['feminine-intelligence'],exclusions:['Emotion is information, not proof; intention is a goal, not manifestation or magical causation.'],contraindicationNotesAr:'النية ما بتضمن النتيجة ولا “تجذب” الواقع؛ هي بس بتوضح شو النتيجة اللي بدك تخدميها.',durationMin:6,stepsAr:['شو الشعور عم يخبرك؟','شو ما بيثبته الشعور؟','شو هدفك الحقيقي: انتقام/كرامة/إصلاح/حماية/وضوح؟','اختاري فعل يخدم الهدف.'],actionTemplateAr:'سمّي الشعور وبعدين سمّي الهدف الحقيقي قبل أي رد.',measurementSpec:basicMeasure('clarity'),followUpSpec:follow('later_today'),fallbackCode:'EMO_NAME_001',requiresUserConfirmation:false,sources:[S.GROSS_ER,S.ACT_FLEX_2024]}),
];
